### ISSUE TITLE
"Run All" is stopped by cells where all code is commented out

### ISSUE THREAD

**Issue by patrick-nicholson** [maxpoint/spylon-kernel#22]
"Run All" in any of its forms (restart, from above, etc.) stops processing cells after it encounters a cell that only consists of comments. 

This example used "Restart & Run All":

![image](https://cloud.githubusercontent.com/assets/7896723/24264518/1627e666-0fd7-11e7-81b9-5f2462a0cf9c.png)

**Comment by parente** [comment]
The Scala interpreter is returning http://www.scala-lang.org/files/archive/nightly/2.12.x/api/2.12.x/scala-compiler/scala/tools/nsc/interpreter/Results$$Incomplete$.html for a comment-only input. It returns the same thing for a cell with code `x = {`.

**Comment by mariusvniekerk** [comment]
Wonder if we can use pygments for this?

**Comment by ericdill** [comment]
> Wonder if we can use pygments for this?

Aren't you on vacation?

**Comment by parente** [comment]
Toree marks all cases of incomplete as a syntax error (https://github.com/apache/incubator-toree/blob/87a9eb8ad08406ce0747e92f7714d4eb54153293/kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/interpreter/tasks/ExecuteRequestTaskActor.scala#L95).

Either we go with that or we start having heuristics for special cases like "all of the lines in the cell are comments."

**Comment by patrick-nicholson** [comment]
Is that the cause of Toree raising sytnax errors when the last line in a cell is a comment?

**Comment by parente** [comment]
Certainly happens when the comment is the only thing in the cell. I don't know if it's the same spot in the code that logs the syntax error for a cell that has some code and a comment on the last line in Toree. (That oddity doesn't happen in spylon-kernel).

I'm leaning toward simply treating `Results.Incomplete` as an error (with output, not the silence it currently logs) and not inventing special parsing logic for the cell-with-comments-only case.

**Comment by mariusvniekerk** [comment]
So Toree executes line by line.  This is basically the exact same problem.

**Comment by mariusvniekerk** [comment]
We can probably parse a scala code block with pygments and determine if it's all "blank".

**Comment by patrick-nicholson** [comment]
Whatever causes this behavior (empty results returned by code-only cell) also worsens #26. If you run a cell with nothing but comments, all future print behaviors are disabled.

**Comment by parente** [comment]
The withOut block wrapping that probably needs to be done per call to interpret to fix #26 will also implicitly fix this.
