### ISSUE TITLE
Use Spark 2.1.1 to support Python 3.6

### ISSUE THREAD

**Issue by basnijholt** [maxpoint/spylon-kernel#27]
[Spark 2.1.1 is released](https://spark.apache.org/news/spark-2-1-1-released.html) and now supports Python 3.6.

**Comment by parente** [comment]
Thanks @basnijholt . I believe the code here should work as-is with Python 3.6 but have not tested it yet. The only mention of the Python 3.5 requirement is in the README which we can remove once we confirm things here are working.

**Comment by parente** [comment]
Ah, and in travis. I'll work on a PR for that after the few outstanding ones merge.
